# Generated by Django 3.2.15 on 2022-08-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BabiesCorner', '0005_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BabiesCorner.shippingaddress'),
        ),
    ]
