# Generated by Django 3.2.15 on 2022-09-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BabiesCorner', '0006_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='extra',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
